# Generated by Django 4.1 on 2022-08-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_wine_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='brand',
        ),
    ]
